### ISSUE TITLE
The exit is a lie

### ISSUE THREAD

**Issue by quasilyte** [Akademya/mandrake#20]
The dwarf said that there is an exit.
But there is none.
A brave Mandrake killed a boss and perished at the second one.
There is nothing, but pain and misery in that place.

I'll never believe a dwarf ever again.

Ahah. I was so shocked that I cloned this game, set all monster's hp to 1, and killed ~10 bosses just to see if there is really nothing in there. xD

**Comment by OsakiTsukiko** [comment]
:skull: yea, the dwarf is lying...
The game was made for a game jam so we didn't have time to implement everything, and most probably Serb nor I will work on it any longer as we both have other projects, it was just a fun experience to challenge ourselves a bit. (The gameplay isn't that fun) Thx for playing it tho :)
